import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

const TEMPLATE_DIRECTORY = '01-模板';
const TEMPLATE_FILE = '教学PPT模板-物理题HTML.html';
const OUTPUT_DIRECTORY = '05-课堂PPT';
const GENERATED_MARKER = '<!-- Generated by Physics Vault html-presentation-workflow. -->';
const OPERATION_MARKER_PREFIX = '<!-- Physics Vault operation-id: ';
const FINGERPRINT_MARKER_PREFIX = '<!-- Physics Vault request-sha256: ';
const IMAGE_EXTENSIONS = new Set(['.png', '.jpg', '.jpeg', '.gif', '.webp', '.svg', '.bmp']);
const TEMPLATE_SIGNATURES = [
  '<main class="deck">',
  'class="slide',
  'id="toggle-answer"',
  'window.MathJax',
  'answers-hidden',
  'question-choice',
  'question-experiment',
  'question-calculation',
];

const QUESTION_TYPES = {
  single_choice: { label: '单选题', layout: 'question-choice' },
  multiple_choice: { label: '多选题', layout: 'question-choice' },
  experiment: { label: '实验题', layout: 'question-experiment' },
  calculation: { label: '计算题', layout: 'question-calculation' },
  fill: { label: '填空题', layout: 'question-experiment' },
  graph: { label: '图像题', layout: 'question-experiment' },
  other: { label: '物理题', layout: 'question-calculation' },
};

function fail(message) {
  throw new Error(message);
}

function within(candidate, parent) {
  const relative = path.relative(parent, candidate);
  return relative === '' || (!relative.startsWith(`..${path.sep}`) && relative !== '..' && !path.isAbsolute(relative));
}

function sha256File(filePath) {
  return crypto.createHash('sha256').update(fs.readFileSync(filePath)).digest('hex');
}

function requiredString(value, label, maxLength = 12000) {
  if (typeof value !== 'string' || !value.trim()) fail(`${label} 必须是非空字符串。`);
  const result = value.trim();
  if (result.length > maxLength) fail(`${label} 不能超过 ${maxLength} 个字符。`);
  return result;
}

function optionalString(value, label, maxLength = 12000) {
  if (value === undefined || value === null || value === '') return undefined;
  return requiredString(value, label, maxLength);
}

function safeFilePart(value, maxLength = 80) {
  return requiredString(value, 'title', maxLength)
    .replace(/[\\/:*?"<>|\r\n]+/g, '-')
    .replace(/\s+/g, ' ')
    .replace(/^\.+|\.+$/g, '')
    .trim() || '未命名课件';
}

function escapeHtml(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
}

function richText(value) {
  return escapeHtml(value).replace(/\r?\n/g, '<br>');
}

function templatePath(resourceRoot) {
  const templates = path.resolve(resourceRoot, TEMPLATE_DIRECTORY);
  const candidate = path.resolve(templates, TEMPLATE_FILE);
  if (!within(candidate, templates) || path.extname(candidate).toLowerCase() !== '.html') fail('HTML 课件模板路径不合法。');
  if (!fs.existsSync(candidate)) fail(`HTML 课件模板不存在：${candidate}`);
  return candidate;
}

function outputPath(resourceRoot, create = false) {
  const output = path.resolve(resourceRoot, OUTPUT_DIRECTORY);
  if (!within(output, resourceRoot) || path.basename(output) !== OUTPUT_DIRECTORY) fail('HTML 课件输出目录不合法。');
  if (create) fs.mkdirSync(path.join(output, 'images'), { recursive: true });
  return output;
}

function nextSequence(output) {
  let highest = 0;
  if (!fs.existsSync(output)) return '001';
  for (const entry of fs.readdirSync(output, { withFileTypes: true })) {
    if (!entry.isFile()) continue;
    const match = /^(\d{3})-/.exec(entry.name);
    if (match) highest = Math.max(highest, Number(match[1]));
  }
  return String(highest + 1).padStart(3, '0');
}

function normalizeStringArray(value, label, { maxItems = 20, maxLength = 4000 } = {}) {
  if (value === undefined || value === null) return [];
  if (!Array.isArray(value)) fail(`${label} 必须是字符串数组。`);
  if (value.length > maxItems) fail(`${label} 最多包含 ${maxItems} 项。`);
  return value.map((item, index) => requiredString(item, `${label}[${index}]`, maxLength));
}

function normalizeInput(input) {
  if (!input || typeof input !== 'object' || Array.isArray(input)) fail('输入必须是对象。');
  const title = requiredString(input.title, 'title', 120);
  if (!Array.isArray(input.questions) || input.questions.length === 0) fail('questions 必须是非空数组。');
  if (input.questions.length > 80) fail('questions 最多包含 80 道题。');
  const questions = input.questions.map((value, index) => {
    if (!value || typeof value !== 'object' || Array.isArray(value)) fail(`questions[${index}] 必须是对象。`);
    const questionType = optionalString(value.question_type, `questions[${index}].question_type`, 32) ?? 'other';
    if (!QUESTION_TYPES[questionType]) fail(`questions[${index}].question_type 不受支持：${questionType}`);
    return {
      questionType,
      title: optionalString(value.title, `questions[${index}].title`, 120) ?? `第 ${index + 1} 题`,
      source: optionalString(value.source, `questions[${index}].source`, 160) ?? '',
      section: optionalString(value.section, `questions[${index}].section`, 80) ?? '',
      stem: requiredString(value.stem, `questions[${index}].stem`, 16000),
      choices: normalizeStringArray(value.choices, `questions[${index}].choices`, { maxItems: 8, maxLength: 2000 }),
      dataItems: normalizeStringArray(value.data_items, `questions[${index}].data_items`, { maxItems: 8, maxLength: 500 }),
      prompt: optionalString(value.prompt, `questions[${index}].prompt`, 4000) ?? '',
      answer: optionalString(value.answer, `questions[${index}].answer`, 4000) ?? '',
      analysis: normalizeStringArray(value.analysis, `questions[${index}].analysis`, { maxItems: 20, maxLength: 4000 }),
      keypoint: optionalString(value.keypoint, `questions[${index}].keypoint`, 4000) ?? '',
      teacherNote: optionalString(value.teacher_note, `questions[${index}].teacher_note`, 2000) ?? '',
      imagePaths: normalizeStringArray(value.image_paths, `questions[${index}].image_paths`, { maxItems: 4, maxLength: 1000 }),
      imageAlts: normalizeStringArray(value.image_alts, `questions[${index}].image_alts`, { maxItems: 4, maxLength: 300 }),
    };
  });
  return {
    title,
    subtitle: optionalString(input.subtitle, 'subtitle', 240) ?? '高中物理课堂题目讲评',
    teacher: optionalString(input.teacher, 'teacher', 80) ?? '待填写',
    grade: optionalString(input.grade, 'grade', 80) ?? '高中',
    lessonType: optionalString(input.lesson_type, 'lesson_type', 80) ?? '讲评',
    school: optionalString(input.school, 'school', 120) ?? '高中物理教学资源库',
    chapter: optionalString(input.chapter, 'chapter', 120) ?? title,
    sectionDescription: optionalString(input.section_description, 'section_description', 240) ?? '进入题目讲评：先独立思考，再逐步揭示答案与解析。',
    questions,
  };
}

function validateImageSource(source, resourceRoot, projectRoot) {
  const resolved = path.resolve(source);
  const allowedRoots = [path.resolve(resourceRoot), path.resolve(projectRoot, 'data')];
  if (!allowedRoots.some((root) => within(resolved, root))) {
    fail(`图片必须位于教学资源库或 Physics Vault 的 data 目录：${source}`);
  }
  if (!fs.existsSync(resolved) || !fs.statSync(resolved).isFile()) fail(`图片不存在：${source}`);
  if (!IMAGE_EXTENSIONS.has(path.extname(resolved).toLowerCase())) fail(`不支持的图片格式：${source}`);
  return resolved;
}

function imagePlan(normalized, resourceRoot, projectRoot, sequence) {
  const deckPrefix = `${sequence}-${safeFilePart(normalized.title)}`;
  return normalized.questions.map((question, questionIndex) => question.imagePaths.map((source, imageIndex) => {
    const resolved = validateImageSource(source, resourceRoot, projectRoot);
    const baseName = path.basename(resolved).replace(/[\\/:*?"<>|\r\n]+/g, '-');
    const filename = `${deckPrefix}__q${questionIndex + 1}-${imageIndex + 1}_${baseName}`;
    return {
      source: resolved,
      filename,
      relative: `./images/${encodeURIComponent(filename)}`,
      alt: question.imageAlts[imageIndex] ?? `第 ${questionIndex + 1} 题配图 ${imageIndex + 1}`,
    };
  }));
}

function footer(chapter, pageNo) {
  return `<div class="footer"><span>${escapeHtml(chapter)}</span><span class="page-no">${String(pageNo).padStart(2, '0')}</span></div>`;
}

function renderCover(input, pageNo) {
  return `<section class="slide cover">
      <div class="cover-tag">高中物理 · HTML 课堂课件</div>
      <div class="cover-grid"><div><h1>${escapeHtml(input.title)}</h1><p class="subtitle">${richText(input.subtitle)}<br>适合课堂讲授、例题精讲、习题讲评、阶段复习。</p></div></div>
      <div class="cover-card"><h3>基本信息</h3><ul class="meta-list"><li>授课教师：${escapeHtml(input.teacher)}</li><li>适用年级：${escapeHtml(input.grade)}</li><li>课时定位：${escapeHtml(input.lessonType)}</li></ul></div>
      ${footer(input.school, pageNo)}
    </section>`;
}

function uniqueSections(questions) {
  return [...new Set(questions.map((question) => question.section).filter(Boolean))];
}

function renderToc(input, pageNo) {
  const sections = uniqueSections(input.questions);
  const cards = [
    '<div class="toc-card"><div class="toc-num">01</div><span>封面与课程信息</span></div>',
    ...(sections.length > 0
      ? sections.slice(0, 8).map((section, index) => `<div class="toc-card example"><div class="toc-num">${String(index + 1).padStart(2, '0')}</div><span>${escapeHtml(section)}</span></div>`)
      : [`<div class="toc-card example"><div class="toc-num">题目</div><span>${input.questions.length} 道题目精讲</span></div>`]),
    '<div class="toc-card practice"><div class="toc-num">H</div><span>按 H 键显示或隐藏答案</span></div>',
  ].join('\n');
  return `<section class="slide">
      <div class="slide-header"><div><div class="pill">内容结构</div><h2 class="slide-title">本节导航</h2><p class="slide-subtitle">题干留在左侧，题图与解析位于右侧，答案默认隐藏。</p></div></div>
      <div style="flex:1;display:flex;flex-direction:column;justify-content:center;gap:12px;"><div class="toc-grid">${cards}</div></div>
      ${footer(input.chapter, pageNo)}
    </section>`;
}

function renderBridge(section, description, chapter, pageNo) {
  return `<section class="slide section-bridge"><div class="bridge-line"></div><div class="bridge-kicker">SECTION BREAK</div><h2>${escapeHtml(section)}</h2><p>${richText(description)}</p>${footer(chapter, pageNo)}</section>`;
}

function renderChoices(choices) {
  if (choices.length === 0) return '';
  const labels = 'ABCDEFGH';
  return `<div class="choices">${choices.map((choice, index) => {
    const hasLabel = /^\s*[A-H][.．、:]\s*/i.test(choice);
    return `<div class="choice">${hasLabel ? richText(choice) : `${labels[index]}. ${richText(choice)}`}</div>`;
  }).join('')}</div>`;
}

function renderDataItems(items) {
  return items.length === 0 ? '' : `<div class="data-strip">${items.map((item) => `<span>${richText(item)}</span>`).join('')}</div>`;
}

function renderImages(images) {
  if (images.length === 0) return '';
  const imageTags = images.map((item) => `<img src="${item.relative}" alt="${escapeHtml(item.alt)}">`).join('');
  return `<div><div class="analysis-figure image-grid image-count-${images.length}">${imageTags}</div></div>`;
}

function renderAnalysis(question) {
  const lines = question.analysis.length > 0 ? question.analysis : ['课堂讲解时在此逐步展示分析过程。'];
  const answer = question.answer ? `<div class="answer-badge" style="margin-top:14px;">答案：${richText(question.answer)}</div>` : '';
  const board = `<div class="blackboard">${lines.map((line) => `<div class="math-line">${richText(line)}</div>`).join('')}</div>`;
  const keypoint = question.keypoint ? `<div class="keypoint" style="margin-top:16px;">${richText(question.keypoint)}</div>` : '';
  return `<div class="analysis-canvas"><div class="analysis-overlay"><h3>解析</h3>${answer}${board}${keypoint}</div></div>`;
}

function renderQuestion(question, images, chapter, pageNo) {
  const type = QUESTION_TYPES[question.questionType];
  const prompt = question.prompt ? `<div class="question-text">${richText(question.prompt)}</div>` : '';
  const note = question.teacherNote ? `<div class="question-meta-note">${richText(question.teacherNote)}</div>` : '';
  return `<section class="slide slide--question">
      <div class="slide-header"><div class="question-topline"><span class="pill">${type.label}</span><span class="headline">${escapeHtml(question.title)}</span>${question.source ? `<span class="divider">|</span><span class="meta">${escapeHtml(question.source)}</span>` : ''}</div></div>
      <div class="two-col question-layout ${type.layout}">
        <article class="question-card"><div class="question-text">${richText(question.stem)}</div>${renderChoices(question.choices)}${renderDataItems(question.dataItems)}${prompt}${note}</article>
        <aside class="analysis-space">${renderImages(images)}${renderAnalysis(question)}</aside>
      </div>
      ${footer(chapter, pageNo)}
    </section>`;
}

function renderDeck(input, images) {
  const slides = [];
  let pageNo = 1;
  slides.push(renderCover(input, pageNo++));
  slides.push(renderToc(input, pageNo++));
  let activeSection;
  input.questions.forEach((question, index) => {
    if (question.section && question.section !== activeSection) {
      activeSection = question.section;
      slides.push(renderBridge(question.section, input.sectionDescription, input.chapter, pageNo++));
    }
    slides.push(renderQuestion(question, images[index], input.chapter, pageNo++));
  });
  return slides;
}

function renderPresentation(template, input, images, requestedOperationId, fingerprint) {
  const slides = renderDeck(input, images);
  const deckMarkup = `<main class="deck">\n${slides.join('\n\n')}\n  </main>`;
  if (!/<main class="deck">[\s\S]*?<\/main>/.test(template)) fail('HTML 模板缺少可替换的 deck 主区域。');
  let rendered = template
    .replace(/<title>[\s\S]*?<\/title>/, `<title>${escapeHtml(input.title)}</title>`)
    .replace(/<main class="deck">[\s\S]*?<\/main>/, deckMarkup)
    .replace(/<div class="deck-indicator" id="deck-indicator">[\s\S]*?<\/div>/, `<div class="deck-indicator" id="deck-indicator">1 / ${slides.length}</div>`)
    .replace('</head>', `<style>
    .analysis-figure.image-grid { display:grid !important; grid-template-columns:repeat(2,minmax(0,1fr)); gap:8px; align-items:center; }
    .analysis-figure.image-grid.image-count-1 { grid-template-columns:1fr; }
    .analysis-figure.image-grid img { width:100%; height:100%; min-height:0; max-height:100%; object-fit:contain; }
  </style>\n</head>`);
  const markers = [GENERATED_MARKER, `${FINGERPRINT_MARKER_PREFIX}${fingerprint} -->`];
  if (requestedOperationId) markers.splice(1, 0, `${OPERATION_MARKER_PREFIX}${requestedOperationId} -->`);
  rendered = rendered.replace(/<!DOCTYPE html>\s*/i, `<!DOCTYPE html>\n${markers.join('\n')}\n`);
  return { rendered, pageCount: slides.length };
}

function requestFingerprint(input) {
  return crypto.createHash('sha256').update(JSON.stringify(input)).digest('hex');
}

function findOperationResult(output, requestedOperationId, fingerprint) {
  if (!requestedOperationId || !fs.existsSync(output)) return undefined;
  const operationMarker = `${OPERATION_MARKER_PREFIX}${requestedOperationId} -->`;
  const fingerprintMarker = `${FINGERPRINT_MARKER_PREFIX}${fingerprint} -->`;
  for (const entry of fs.readdirSync(output, { withFileTypes: true })) {
    if (!entry.isFile() || path.extname(entry.name).toLowerCase() !== '.html') continue;
    const candidate = path.join(output, entry.name);
    const source = fs.readFileSync(candidate, 'utf8');
    if (!source.includes(operationMarker)) continue;
    if (!source.includes(fingerprintMarker)) fail(`operation_id ${requestedOperationId} 已用于不同的 HTML 课件内容，请改用新的 operation_id。`);
    return candidate;
  }
  return undefined;
}

function operationId(value) {
  if (value === undefined || value === null || value === '') return undefined;
  const result = requiredString(value, 'operation_id', 80);
  if (!/^[A-Za-z0-9_-]+$/.test(result)) fail('operation_id 只能包含字母、数字、下划线和连字符。');
  return result;
}

export function auditHtmlPresentationTemplate(resourceRoot) {
  const source = templatePath(resourceRoot);
  const body = fs.readFileSync(source, 'utf8');
  const missingSignatures = TEMPLATE_SIGNATURES.filter((signature) => !body.includes(signature));
  return {
    template_id: 'physics-question-html',
    template_file: source,
    actual_sha256: sha256File(source),
    passed: missingSignatures.length === 0,
    missing_signatures: missingSignatures,
    output_directory: outputPath(resourceRoot),
    output_exists: fs.existsSync(outputPath(resourceRoot)),
  };
}

export function htmlPresentationTemplateInfo(resourceRoot) {
  const audit = auditHtmlPresentationTemplate(resourceRoot);
  return {
    ...audit,
    name: '高中物理题 HTML 课堂课件',
    description: '生成 16:9 全屏网页课件，支持键盘翻页、MathJax 公式、题图和答案显隐。',
    question_types: Object.keys(QUESTION_TYPES),
    image_policy: '图片只允许来自教学资源库或 Physics Vault/data，生成时复制到课件 images 目录。',
    offline_note: '模板默认从 jsDelivr 加载 MathJax；无网络时普通文字和翻页可用，公式渲染可能不可用。',
  };
}

export function createHtmlPresentation(input, { resourceRoot, projectRoot }) {
  const normalized = normalizeInput(input);
  const audit = auditHtmlPresentationTemplate(resourceRoot);
  if (!audit.passed) fail(`HTML 课件模板结构检查失败：缺少 ${audit.missing_signatures.join(', ')}`);
  const output = outputPath(resourceRoot);
  const requestedOperationId = operationId(input.operation_id);
  const fingerprint = requestFingerprint({ ...normalized, operation_id: undefined });
  const existing = findOperationResult(output, requestedOperationId, fingerprint);
  if (existing) {
    return { status: 'existing', source_path: existing, operation_id: requestedOperationId, idempotent: true, template_sha256: audit.actual_sha256 };
  }
  const sequence = nextSequence(output);
  const filename = `${sequence}-${safeFilePart(normalized.title)}-HTML.html`;
  const sourcePath = path.resolve(output, filename);
  if (!within(sourcePath, output)) fail('生成的 HTML 文件路径不合法。');
  const images = imagePlan(normalized, resourceRoot, projectRoot, sequence);
  const template = fs.readFileSync(audit.template_file, 'utf8');
  const { rendered, pageCount } = renderPresentation(template, normalized, images, requestedOperationId, fingerprint);
  if (input.dry_run === true) {
    return {
      status: 'preview', source_path: sourcePath, output_directory: output, sequence,
      page_count: pageCount, question_count: normalized.questions.length,
      image_count: images.flat().length, template_sha256: audit.actual_sha256,
      operation_id: requestedOperationId, message: '预览不会写入教学资源库。',
    };
  }
  outputPath(resourceRoot, true);
  fs.writeFileSync(sourcePath, rendered, { encoding: 'utf8', flag: 'wx' });
  try {
    for (const item of images.flat()) {
      fs.copyFileSync(item.source, path.join(output, 'images', item.filename), fs.constants.COPYFILE_EXCL);
    }
  } catch (error) {
    fs.rmSync(sourcePath, { force: true });
    throw error;
  }
  return {
    status: 'created', source_path: sourcePath, output_directory: output, images_directory: path.join(output, 'images'),
    sequence, page_count: pageCount, question_count: normalized.questions.length, image_count: images.flat().length,
    template_sha256: audit.actual_sha256, operation_id: requestedOperationId, idempotent: false,
    next_action: '调用 validate_html_presentation 检查页面、占位符和图片引用，然后用浏览器打开 source_path 上课。',
  };
}

export function validateHtmlPresentation(input, { resourceRoot }) {
  const output = outputPath(resourceRoot);
  const source = path.resolve(requiredString(input.source_path, 'source_path', 1000));
  if (!within(source, output) || path.extname(source).toLowerCase() !== '.html') fail(`source_path 必须是 ${OUTPUT_DIRECTORY} 内的 .html 文件。`);
  if (!fs.existsSync(source)) fail(`HTML 课件不存在：${source}`);
  const body = fs.readFileSync(source, 'utf8');
  if (!body.includes(GENERATED_MARKER)) fail('只允许校验由 Physics Vault HTML 课件 MCP 创建的文件。');
  const unresolved = [...body.matchAll(/\{\{[^}]+\}\}/g)].map((match) => match[0]);
  const localImages = [...body.matchAll(/<img\s+[^>]*src="(\.\/[^\"]+)"/g)].map((match) => decodeURIComponent(match[1]));
  const missingImages = localImages.filter((relative) => {
    const candidate = path.resolve(path.dirname(source), relative);
    return !within(candidate, output) || !fs.existsSync(candidate);
  });
  const slideCount = (body.match(/<section class="slide(?:\s|\")/g) ?? []).length;
  const questionCount = (body.match(/<section class="slide slide--question">/g) ?? []).length;
  const errors = [];
  if (slideCount === 0) errors.push('未检测到幻灯片页面。');
  if (questionCount === 0) errors.push('未检测到题目页面。');
  if (unresolved.length > 0) errors.push(`仍有 ${unresolved.length} 个未替换占位符。`);
  if (missingImages.length > 0) errors.push(`有 ${missingImages.length} 个图片引用缺失。`);
  return {
    status: errors.length === 0 ? 'validated' : 'invalid', source_path: source,
    slide_count: slideCount, question_count: questionCount, local_image_count: localImages.length,
    unresolved_placeholders: unresolved, missing_images: missingImages, errors,
    warnings: body.includes('https://cdn.jsdelivr.net/npm/mathjax') ? ['公式依赖在线 MathJax；离线课堂请提前确认网络。'] : [],
  };
}

const questionSchema = {
  type: 'object',
  properties: {
    question_type: { type: 'string', enum: Object.keys(QUESTION_TYPES), default: 'other' },
    title: { type: 'string' }, source: { type: 'string' }, section: { type: 'string' }, stem: { type: 'string' },
    choices: { type: 'array', maxItems: 8, items: { type: 'string' } },
    data_items: { type: 'array', maxItems: 8, items: { type: 'string' } },
    prompt: { type: 'string' }, answer: { type: 'string' },
    analysis: { type: 'array', maxItems: 20, items: { type: 'string' } },
    keypoint: { type: 'string' }, teacher_note: { type: 'string' },
    image_paths: { type: 'array', maxItems: 4, items: { type: 'string' } },
    image_alts: { type: 'array', maxItems: 4, items: { type: 'string' } },
  },
  required: ['stem'],
  additionalProperties: false,
};

export const htmlPresentationTools = [
  { name: 'get_html_presentation_template', description: '检查高中物理 HTML 课件模板、输出目录、题型和图片规则。', inputSchema: { type: 'object', properties: {}, additionalProperties: false } },
  { name: 'create_html_presentation', description: '把结构化物理题生成可全屏放映的 HTML 课件。含封面、导航、章节过渡、题图、MathJax 公式和答案显隐；dry_run=true 时只预览路径与页数。', inputSchema: { type: 'object', properties: {
    title: { type: 'string' }, subtitle: { type: 'string' }, teacher: { type: 'string' }, grade: { type: 'string' }, lesson_type: { type: 'string' }, school: { type: 'string' }, chapter: { type: 'string' }, section_description: { type: 'string' },
    questions: { type: 'array', minItems: 1, maxItems: 80, items: questionSchema },
    operation_id: { type: 'string', pattern: '^[A-Za-z0-9_-]{1,80}$' }, dry_run: { type: 'boolean', default: false },
  }, required: ['title', 'questions'], additionalProperties: false } },
  { name: 'validate_html_presentation', description: '校验 MCP 生成的 HTML 课件页数、题目页、未替换占位符和本地图片引用。', inputSchema: { type: 'object', properties: { source_path: { type: 'string' } }, required: ['source_path'], additionalProperties: false } },
  { name: 'audit_html_presentation_template', description: '只读检查 HTML 课件模板的结构特征并返回当前 SHA-256。', inputSchema: { type: 'object', properties: {}, additionalProperties: false } },
];
