import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';

const TEMPLATE_DIRECTORY = '01-模板';
const TEMPLATE_FILE = '教学PPT模板-物理题Typst.typ';
const OUTPUT_DIRECTORY = '05-课堂PPT';
const GENERATED_MARKER = '// Generated by Physics Vault typst-presentation-workflow.';
const CONTENT_MARKER = '// {{GENERATED_CONTENT}}';
const MANIFEST_SUFFIX = '.manifest.json';
const IMAGE_EXTENSIONS = new Set(['.png', '.jpg', '.jpeg', '.gif', '.webp', '.svg', '.bmp']);
const QUESTION_TYPES = new Set(['single_choice', 'multiple_choice', 'experiment', 'calculation', 'fill', 'graph', 'other']);
const TEMPLATE_SIGNATURES = ['#set page(', '#let cover-slide(', '#let question-slide(', '#let answer-slide(', '#let closing-slide(', CONTENT_MARKER];

function fail(message) { throw new Error(message); }

function within(candidate, parent) {
  const relative = path.relative(parent, candidate);
  return relative === '' || (!relative.startsWith(`..${path.sep}`) && relative !== '..' && !path.isAbsolute(relative));
}

function requiredString(value, label, maxLength = 12000) {
  if (typeof value !== 'string' || !value.trim()) fail(`${label} 必须是非空字符串。`);
  const result = value.trim();
  if (result.length > maxLength) fail(`${label} 不能超过 ${maxLength} 个字符。`);
  return result;
}

function optionalString(value, label, maxLength = 12000) {
  if (value === undefined || value === null || value === '') return undefined;
  return requiredString(value, label, maxLength);
}

function strings(value, label, maxItems, maxLength) {
  if (value === undefined || value === null) return [];
  if (!Array.isArray(value)) fail(`${label} 必须是字符串数组。`);
  if (value.length > maxItems) fail(`${label} 最多包含 ${maxItems} 项。`);
  return value.map((item, index) => requiredString(item, `${label}[${index}]`, maxLength));
}

function safeFilePart(value) {
  return requiredString(value, 'title', 80).replace(/[\\/:*?"<>|\r\n]+/g, '-').replace(/\s+/g, ' ').replace(/^\.+|\.+$/g, '').trim() || '未命名课件';
}

function sha256File(filePath) {
  return crypto.createHash('sha256').update(fs.readFileSync(filePath)).digest('hex');
}

function fingerprint(value) {
  return crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex');
}

function outputDirectory(resourceRoot, create = false) {
  const output = path.resolve(resourceRoot, OUTPUT_DIRECTORY);
  if (!within(output, resourceRoot) || path.basename(output) !== OUTPUT_DIRECTORY) fail('Typst 课件输出目录不合法。');
  if (create) fs.mkdirSync(path.join(output, 'images'), { recursive: true });
  return output;
}

function templatePath(resourceRoot) {
  const templates = path.resolve(resourceRoot, TEMPLATE_DIRECTORY);
  const source = path.resolve(templates, TEMPLATE_FILE);
  if (!within(source, templates) || path.extname(source).toLowerCase() !== '.typ') fail('Typst 课件模板路径不合法。');
  if (!fs.existsSync(source)) fail(`Typst 课件模板不存在：${source}`);
  return source;
}

function nextSequence(output) {
  let highest = 0;
  if (!fs.existsSync(output)) return '001';
  for (const entry of fs.readdirSync(output, { withFileTypes: true })) {
    if (!entry.isFile()) continue;
    const match = /^(\d{3})-/.exec(entry.name);
    if (match) highest = Math.max(highest, Number(match[1]));
  }
  return String(highest + 1).padStart(3, '0');
}

function normalizeInput(input, resourceRoot, projectRoot) {
  if (!input || typeof input !== 'object' || Array.isArray(input)) fail('输入必须是对象。');
  const title = requiredString(input.title, 'title', 120);
  if (!Array.isArray(input.questions) || input.questions.length === 0) fail('questions 必须是非空数组。');
  if (input.questions.length > 60) fail('questions 最多包含 60 道题。');
  const questions = input.questions.map((question, index) => {
    if (!question || typeof question !== 'object' || Array.isArray(question)) fail(`questions[${index}] 必须是对象。`);
    const questionType = optionalString(question.question_type, `questions[${index}].question_type`, 32) ?? 'other';
    if (!QUESTION_TYPES.has(questionType)) fail(`questions[${index}].question_type 不受支持：${questionType}`);
    const imagePaths = strings(question.image_paths, `questions[${index}].image_paths`, 4, 1000).map((source) => {
      const resolved = path.resolve(source);
      const allowedRoots = [path.resolve(resourceRoot), path.resolve(projectRoot, 'data')];
      if (!allowedRoots.some((root) => within(resolved, root))) fail(`图片必须位于教学资源库或 Physics Vault/data：${source}`);
      if (!fs.existsSync(resolved) || !fs.statSync(resolved).isFile()) fail(`图片不存在：${source}`);
      if (!IMAGE_EXTENSIONS.has(path.extname(resolved).toLowerCase())) fail(`不支持的图片格式：${source}`);
      return resolved;
    });
    return {
      questionType,
      title: optionalString(question.title, `questions[${index}].title`, 120) ?? `第 ${index + 1} 题`,
      source: optionalString(question.source, `questions[${index}].source`, 160) ?? '',
      section: optionalString(question.section, `questions[${index}].section`, 80) ?? '',
      stem: requiredString(question.stem, `questions[${index}].stem`, 12000),
      choices: strings(question.choices, `questions[${index}].choices`, 8, 1800),
      dataItems: strings(question.data_items, `questions[${index}].data_items`, 8, 500),
      prompt: optionalString(question.prompt, `questions[${index}].prompt`, 4000) ?? '',
      answer: optionalString(question.answer, `questions[${index}].answer`, 3000) ?? '',
      analysis: strings(question.analysis, `questions[${index}].analysis`, 16, 3000),
      keypoint: optionalString(question.keypoint, `questions[${index}].keypoint`, 2400) ?? '',
      teacherNote: optionalString(question.teacher_note, `questions[${index}].teacher_note`, 1600) ?? '',
      imagePaths,
      imageAlts: strings(question.image_alts, `questions[${index}].image_alts`, 4, 300),
    };
  });
  return {
    title,
    subtitle: optionalString(input.subtitle, 'subtitle', 240) ?? '高中物理课堂题目讲评',
    teacher: optionalString(input.teacher, 'teacher', 80) ?? '待填写',
    grade: optionalString(input.grade, 'grade', 80) ?? '高中',
    lessonType: optionalString(input.lesson_type, 'lesson_type', 80) ?? '讲评',
    school: optionalString(input.school, 'school', 120) ?? '高中物理教学资源库',
    chapter: optionalString(input.chapter, 'chapter', 120) ?? title,
    questions,
  };
}

function typstString(value) {
  return `"${String(value).replaceAll('\\', '\\\\').replaceAll('"', '\\"').replaceAll('\r', '').replaceAll('\n', '\\n')}"`;
}

function splitMath(value) {
  const source = String(value ?? '');
  const tokens = [];
  const pattern = /\$\$([\s\S]+?)\$\$|\$([^$\r\n]+?)\$|\\\(([\s\S]+?)\\\)|\\\[([\s\S]+?)\\\]/g;
  let cursor = 0;
  let match;
  while ((match = pattern.exec(source)) !== null) {
    if (match.index > cursor) tokens.push({ kind: 'text', value: source.slice(cursor, match.index) });
    tokens.push({ kind: 'math', value: match[1] ?? match[2] ?? match[3] ?? match[4] ?? '' });
    cursor = match.index + match[0].length;
  }
  if (cursor < source.length) tokens.push({ kind: 'text', value: source.slice(cursor) });
  return tokens;
}

function latexToTypst(value) {
  let result = String(value ?? '').trim();
  for (let pass = 0; pass < 5; pass += 1) {
    result = result.replace(/\\(?:d?frac)\{([^{}]+)\}\{([^{}]+)\}/g, '($1)/($2)');
    result = result.replace(/\\sqrt\{([^{}]+)\}/g, 'sqrt($1)');
  }
  result = result.replace(/\\(?:text|mathrm|operatorname)\{([^{}]*)\}/g, (_, text) => typstString(text));
  result = result.replace(/\\vec\{([^{}]+)\}/g, 'arrow($1)');
  result = result.replace(/\\overline\{([^{}]+)\}/g, 'overline($1)');
  result = result.replace(/_\{([^{}]+)\}/g, '_($1)').replace(/\^\{([^{}]+)\}/g, '^($1)');
  result = result.replace(/(_(?:\([^)]+\)|[A-Za-z0-9]))(?=[A-Za-z])/g, '$1 ');
  result = result.replace(/\\(?:left|right|displaystyle|textstyle|quad|qquad)\b/g, ' ');
  const commands = {
    times: 'times', cdot: 'dot', pm: 'plus.minus', mp: 'minus.plus',
    leq: '<=', le: '<=', geq: '>=', ge: '>=', neq: '!=', approx: 'approx',
    rightarrow: 'arrow.r', leftarrow: 'arrow.l', to: 'arrow.r', infinity: 'infinity',
    sum: 'sum', prod: 'product', int: 'integral', Delta: 'Delta', theta: 'theta', omega: 'omega',
    alpha: 'alpha', beta: 'beta', gamma: 'gamma', mu: 'mu', rho: 'rho', lambda: 'lambda', pi: 'pi',
  };
  result = result.replace(/\\([A-Za-z]+)/g, (_, name) => ` ${commands[name] ?? name} `);
  result = result.replace(/\\[,;!]/g, ' ');
  result = result.replace(/[{}]/g, (token) => token === '{' ? '(' : ')');
  return result.replace(/\s+/g, ' ').trim();
}

function typstContent(value) {
  const pieces = [];
  for (const token of splitMath(value)) {
    if (token.kind === 'math') {
      pieces.push(`$${latexToTypst(token.value)}$`);
      continue;
    }
    const lines = token.value.replace(/\r\n?/g, '\n').split('\n');
    lines.forEach((line, index) => {
      if (line) pieces.push(`#text(${typstString(line)})`);
      if (index < lines.length - 1) pieces.push('#linebreak()');
    });
  }
  return `[${pieces.join(' ')}]`;
}

function tupleContent(values) {
  if (values.length === 0) return '()';
  return `(${values.map((value) => `${typstContent(value)},`).join(' ')})`;
}

function typeLabel(value) {
  return ({ single_choice: '单选题', multiple_choice: '多选题', experiment: '实验题', calculation: '计算题', fill: '填空题', graph: '图像题', other: '物理题' })[value] ?? '物理题';
}

function imagePlan(normalized, output, sequence) {
  const deckPrefix = `${sequence}-${safeFilePart(normalized.title)}-TYPST`;
  return normalized.questions.map((question, questionIndex) => question.imagePaths.map((source, imageIndex) => {
    const filename = `${deckPrefix}__q${questionIndex + 1}-${imageIndex + 1}_${path.basename(source).replace(/[\\/:*?"<>|\r\n]+/g, '-')}`;
    return { source, filename, destination: path.join(output, 'images', filename), relative: `images/${filename}`.replaceAll('\\', '/') };
  }));
}

function renderSlides(template, input, images, operationId, requestSha) {
  const slides = [];
  slides.push(`#cover-slide(${typstString(input.title)}, ${typstString(input.subtitle)}, ${typstString(input.grade)}, ${typstString(input.lessonType)}, ${typstString(input.teacher)}, ${typstString(input.school)}, ${input.questions.length})`);
  input.questions.forEach((question, index) => {
    slides.push('#pagebreak()');
    slides.push(`#question-slide(
  ${index + 1}, ${typstString(typeLabel(question.questionType))}, ${typstString(question.title)}, ${typstString(question.source)}, ${typstString(input.chapter)},
  ${typstContent(question.stem)},
  choices: ${tupleContent(question.choices)},
  data: ${tupleContent(question.dataItems)},
  prompt: ${typstContent(question.prompt)},
  image-paths: (${images[index].map((item) => `${typstString(item.relative)},`).join(' ')}),
)`);
    slides.push('#pagebreak()');
    const analysis = question.analysis.length > 0 ? question.analysis : ['课堂讲解时补充分步解析。'];
    slides.push(`#answer-slide(
  ${index + 1}, ${typstString(question.title)}, ${typstString(input.chapter)},
  ${typstContent(question.answer || '答案见课堂讲解')},
  ${tupleContent(analysis)},
  ${typstContent(question.keypoint)},
  ${typstContent(question.stem.length > 260 ? `${question.stem.slice(0, 257)}…` : question.stem)},
)`);
  });
  slides.push('#pagebreak()');
  slides.push(`#closing-slide(${typstString(input.chapter)}, ${input.questions.length})`);
  const generated = `${GENERATED_MARKER}\n// Physics Vault operation-id: ${operationId ?? 'none'}\n// Physics Vault request-sha256: ${requestSha}\n#set document(title: ${typstString(input.title)}, author: ${typstString(input.teacher)}, date: none)\n\n${slides.join('\n\n')}\n`;
  if (!template.includes(CONTENT_MARKER)) fail('Typst 课件模板缺少内容插入标记。');
  return template.replace(CONTENT_MARKER, generated);
}

function typstExecutable() {
  return process.env.PHYSICS_TYPST_BIN || 'typst';
}

function compileTypst(sourcePath, pdfPath, resourceRoot) {
  const result = spawnSync(typstExecutable(), ['compile', '--root', resourceRoot, sourcePath, pdfPath], {
    encoding: 'utf8', timeout: 120000, maxBuffer: 20 * 1024 * 1024,
  });
  if (result.error) fail(`无法启动 Typst：${result.error.message}`);
  if (result.status !== 0) fail(`Typst 课件编译失败：${result.stderr || result.stdout || '未返回错误信息'}`);
}

function pdfPageCount(pdfPath) {
  let executable = process.env.PHYSICS_PDFINFO_BIN || 'pdfinfo';
  if (process.platform === 'win32' && !process.env.PHYSICS_PDFINFO_BIN) {
    const located = spawnSync('where.exe', ['pdfinfo'], { encoding: 'utf8', timeout: 10000 });
    const shim = located.status === 0 ? located.stdout.split(/\r?\n/).find(Boolean)?.trim() : undefined;
    if (shim?.toLowerCase().endsWith('.cmd')) {
      const bundled = path.resolve(path.dirname(shim), '..', '..', 'native', 'poppler', 'Library', 'bin', 'pdfinfo.exe');
      if (fs.existsSync(bundled)) executable = bundled;
    } else if (shim) {
      executable = shim;
    }
  }
  const result = spawnSync(executable, [pdfPath], { encoding: 'utf8', timeout: 30000, maxBuffer: 4 * 1024 * 1024 });
  if (result.error || result.status !== 0) return undefined;
  const match = /^Pages:\s+(\d+)\s*$/mi.exec(result.stdout);
  return match ? Number(match[1]) : undefined;
}

function operationId(value) {
  if (value === undefined || value === null || value === '') return undefined;
  const result = requiredString(value, 'operation_id', 80);
  if (!/^[A-Za-z0-9_-]+$/.test(result)) fail('operation_id 只能包含字母、数字、下划线和连字符。');
  return result;
}

function manifests(output) {
  if (!fs.existsSync(output)) return [];
  return fs.readdirSync(output, { withFileTypes: true }).filter((entry) => entry.isFile() && entry.name.endsWith(MANIFEST_SUFFIX)).map((entry) => path.join(output, entry.name));
}

function findExisting(output, requestedOperationId, requestSha) {
  if (!requestedOperationId) return undefined;
  for (const manifestPath of manifests(output)) {
    const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
    if (manifest.generator !== 'Physics Vault typst-presentation-workflow' || manifest.operation_id !== requestedOperationId) continue;
    if (manifest.request_sha256 !== requestSha) fail(`operation_id ${requestedOperationId} 已用于不同的 Typst 课件内容。`);
    if (!fs.existsSync(manifest.source_path) || !fs.existsSync(manifest.pdf_path)) fail(`operation_id ${requestedOperationId} 的成品已缺失。`);
    return manifest;
  }
  return undefined;
}

export function auditTypstPresentationTemplate(resourceRoot) {
  const source = templatePath(resourceRoot);
  const body = fs.readFileSync(source, 'utf8');
  const missingSignatures = TEMPLATE_SIGNATURES.filter((signature) => !body.includes(signature));
  const version = spawnSync(typstExecutable(), ['--version'], { encoding: 'utf8', timeout: 10000 });
  return {
    template_id: 'physics-question-typst',
    template_file: source,
    actual_sha256: sha256File(source),
    typst_version: version.status === 0 ? version.stdout.trim() : null,
    passed: missingSignatures.length === 0 && version.status === 0,
    missing_signatures: missingSignatures,
    output_directory: outputDirectory(resourceRoot),
    output_exists: fs.existsSync(outputDirectory(resourceRoot)),
  };
}

export function typstPresentationInfo(resourceRoot) {
  return {
    ...auditTypstPresentationTemplate(resourceRoot),
    name: '高中物理 Typst PDF 课堂课件',
    description: '生成 16:9 Typst 源文件和 PDF 幻灯片；公式由 Typst 原生排版，完全离线。',
    formula_mode: '输入中的常见 LaTeX 公式会转换为 Typst 数学语法；分式、根式、上下标和单位直接写入 PDF。',
    question_types: [...QUESTION_TYPES],
  };
}

export function createTypstPresentation(input, { resourceRoot, projectRoot }) {
  const normalized = normalizeInput(input, resourceRoot, projectRoot);
  const audit = auditTypstPresentationTemplate(resourceRoot);
  if (!audit.passed) fail(`Typst 课件环境未就绪：${audit.missing_signatures.join(', ') || 'Typst 不可用'}`);
  const output = outputDirectory(resourceRoot);
  const requestedOperationId = operationId(input.operation_id);
  const requestSha = fingerprint(normalized);
  const existing = findExisting(output, requestedOperationId, requestSha);
  if (existing) return { status: 'existing', ...existing, idempotent: true };
  const sequence = nextSequence(output);
  const stem = `${sequence}-${safeFilePart(normalized.title)}-TYPST`;
  const sourcePath = path.resolve(output, `${stem}.typ`);
  const pdfPath = path.resolve(output, `${stem}.pdf`);
  if (!within(sourcePath, output) || !within(pdfPath, output)) fail('Typst 课件输出路径不合法。');
  const slideCount = normalized.questions.length * 2 + 2;
  const images = imagePlan(normalized, output, sequence);
  if (input.dry_run === true) {
    return { status: 'preview', source_path: sourcePath, pdf_path: pdfPath, output_directory: output, sequence, slide_count: slideCount, question_count: normalized.questions.length, image_count: images.flat().length, operation_id: requestedOperationId, message: '预览不会写入教学资源库。' };
  }
  outputDirectory(resourceRoot, true);
  const source = renderSlides(fs.readFileSync(audit.template_file, 'utf8'), normalized, images, requestedOperationId, requestSha);
  const createdImages = [];
  try {
    for (const item of images.flat()) {
      fs.copyFileSync(item.source, item.destination, fs.constants.COPYFILE_EXCL);
      createdImages.push(item.destination);
    }
    fs.writeFileSync(sourcePath, source, { encoding: 'utf8', flag: 'wx' });
    compileTypst(sourcePath, pdfPath, resourceRoot);
    const actualPages = pdfPageCount(pdfPath);
    if (actualPages !== slideCount) fail(`Typst 课件页数异常：预期 ${slideCount} 页，实际 ${actualPages ?? '无法读取'} 页。`);
    const manifest = {
      schema_version: 1,
      generator: 'Physics Vault typst-presentation-workflow',
      source_path: sourcePath,
      pdf_path: pdfPath,
      output_directory: output,
      sequence,
      slide_count: slideCount,
      question_count: normalized.questions.length,
      image_count: images.flat().length,
      operation_id: requestedOperationId,
      request_sha256: requestSha,
      template_sha256: audit.actual_sha256,
      source_sha256: sha256File(sourcePath),
      pdf_sha256: sha256File(pdfPath),
      created_at: new Date().toISOString(),
    };
    fs.writeFileSync(`${sourcePath}${MANIFEST_SUFFIX}`, JSON.stringify(manifest, null, 2), { encoding: 'utf8', flag: 'wx' });
    return { status: 'created', ...manifest, idempotent: false, next_action: '调用 validate_typst_presentation 校验源文件、PDF 页数和哈希，然后用 PDF 阅读器全屏放映。' };
  } catch (error) {
    fs.rmSync(sourcePath, { force: true });
    fs.rmSync(pdfPath, { force: true });
    for (const image of createdImages) fs.rmSync(image, { force: true });
    throw error;
  }
}

export function validateTypstPresentation(input, { resourceRoot }) {
  const output = outputDirectory(resourceRoot);
  const source = path.resolve(requiredString(input.source_path, 'source_path', 1000));
  if (!within(source, output) || path.extname(source).toLowerCase() !== '.typ') fail(`source_path 必须是 ${OUTPUT_DIRECTORY} 内的 .typ 文件。`);
  if (!fs.existsSync(source)) fail(`Typst 课件不存在：${source}`);
  const body = fs.readFileSync(source, 'utf8');
  const manifestPath = `${source}${MANIFEST_SUFFIX}`;
  if (!body.includes(GENERATED_MARKER) || !fs.existsSync(manifestPath)) fail('只允许校验由 Physics Vault Typst 课件 MCP 创建的文件。');
  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
  const errors = [];
  if (!fs.existsSync(manifest.pdf_path)) errors.push('PDF 成品缺失。');
  if (body.includes(CONTENT_MARKER)) errors.push('仍有未替换的模板占位符。');
  if (manifest.source_sha256 !== sha256File(source)) errors.push('Typst 源文件哈希与清单不一致。');
  let pages;
  if (fs.existsSync(manifest.pdf_path)) {
    if (manifest.pdf_sha256 !== sha256File(manifest.pdf_path)) errors.push('PDF 哈希与清单不一致。');
    pages = pdfPageCount(manifest.pdf_path);
    if (pages !== manifest.slide_count) errors.push(`PDF 页数不一致：预期 ${manifest.slide_count}，实际 ${pages ?? '无法读取'}。`);
  }
  return {
    status: errors.length === 0 ? 'validated' : 'invalid',
    source_path: source,
    pdf_path: manifest.pdf_path,
    manifest_path: manifestPath,
    slide_count: pages ?? manifest.slide_count,
    question_count: manifest.question_count,
    image_count: manifest.image_count,
    source_sha256: sha256File(source),
    pdf_sha256: fs.existsSync(manifest.pdf_path) ? sha256File(manifest.pdf_path) : null,
    errors,
  };
}

const questionSchema = {
  type: 'object',
  properties: {
    question_type: { type: 'string', enum: [...QUESTION_TYPES], default: 'other' }, title: { type: 'string' }, source: { type: 'string' }, section: { type: 'string' }, stem: { type: 'string' },
    choices: { type: 'array', maxItems: 8, items: { type: 'string' } }, data_items: { type: 'array', maxItems: 8, items: { type: 'string' } }, prompt: { type: 'string' }, answer: { type: 'string' }, analysis: { type: 'array', maxItems: 16, items: { type: 'string' } }, keypoint: { type: 'string' }, teacher_note: { type: 'string' }, image_paths: { type: 'array', maxItems: 4, items: { type: 'string' } }, image_alts: { type: 'array', maxItems: 4, items: { type: 'string' } },
  }, required: ['stem'], additionalProperties: false,
};

export const typstPresentationTools = [
  { name: 'get_typst_presentation_template', description: '检查高中物理 Typst 课件模板、Typst 编译器、题型和公式策略。', inputSchema: { type: 'object', properties: {}, additionalProperties: false } },
  { name: 'create_typst_presentation', description: '把结构化物理题生成 16:9 Typst 源文件和 PDF 幻灯片；公式使用 Typst 原生排版，完全离线。dry_run=true 时只预览。', inputSchema: { type: 'object', properties: {
    title: { type: 'string' }, subtitle: { type: 'string' }, teacher: { type: 'string' }, grade: { type: 'string' }, lesson_type: { type: 'string' }, school: { type: 'string' }, chapter: { type: 'string' }, questions: { type: 'array', minItems: 1, maxItems: 60, items: questionSchema }, operation_id: { type: 'string', pattern: '^[A-Za-z0-9_-]{1,80}$' }, dry_run: { type: 'boolean', default: false },
  }, required: ['title', 'questions'], additionalProperties: false } },
  { name: 'validate_typst_presentation', description: '校验 MCP 生成的 Typst 课件源文件、PDF 页数、模板占位符和文件哈希。', inputSchema: { type: 'object', properties: { source_path: { type: 'string' } }, required: ['source_path'], additionalProperties: false } },
  { name: 'audit_typst_presentation_template', description: '只读检查 Typst 课件模板结构、当前 SHA-256 与编译器版本。', inputSchema: { type: 'object', properties: {}, additionalProperties: false } },
];
