#!/usr/bin/env node

/**
 * Study-sheet workflow MCP.
 *
 * This server deliberately lives in Physics Vault.  It treats the teaching
 * resource library as an external, guarded content root: templates are read
 * and hash-checked there, while generated study sheets are written only to
 * the registry-declared output folders in that same library.
 */

import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import readline from 'node:readline';
import { fileURLToPath } from 'node:url';

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.resolve(scriptDirectory, '..');
const templateDirectoryName = '01-模板';
const generatedMarker = '// Generated by Physics Vault study-sheet-workflow.';
const operationMarkerPrefix = '// Physics Vault operation-id: ';
const outputDirectoryNames = new Set(['02-知识讲义', '03-阶段检测', '04-每日一题']);

function fail(message) {
  throw new Error(message);
}

function requiredString(value, label, { maxLength = 12000 } = {}) {
  if (typeof value !== 'string' || !value.trim()) fail(`${label} 必须是非空字符串。`);
  const result = value.trim();
  if (result.length > maxLength) fail(`${label} 不能超过 ${maxLength} 个字符。`);
  return result;
}

function nullableString(value, label, options) {
  if (value === undefined || value === null || value === '') return undefined;
  return requiredString(value, label, options);
}

function operationId(value) {
  if (value === undefined || value === null || value === '') return undefined;
  const result = requiredString(value, 'operation_id', { maxLength: 80 });
  if (!/^[A-Za-z0-9_-]+$/.test(result)) fail('operation_id 只能包含字母、数字、下划线和连字符。');
  return result;
}

function sha256(filePath) {
  return crypto.createHash('sha256').update(fs.readFileSync(filePath)).digest('hex');
}

function resolveStudySheetRoot() {
  const configured = process.env.PHYSICS_STUDY_SHEET_ROOT;
  if (!configured) {
    fail('未配置 PHYSICS_STUDY_SHEET_ROOT。请在 Physics Vault 的本机 MCP 配置中指定教学资源库根目录。');
  }
  const root = path.resolve(configured);
  if (!fs.existsSync(root)) fail(`教学资源库不存在：${root}`);
  return root;
}

function within(candidate, parent) {
  const relative = path.relative(parent, candidate);
  return relative === '' || (!relative.startsWith(`..${path.sep}`) && relative !== '..' && !path.isAbsolute(relative));
}

function resourcePaths() {
  const root = resolveStudySheetRoot();
  const templates = path.join(root, templateDirectoryName);
  const registry = path.join(templates, 'templates.json');
  if (!fs.existsSync(registry)) fail(`模板注册表不存在：${registry}`);
  return { root, templates, registry };
}

function loadRegistry() {
  const { registry } = resourcePaths();
  const value = JSON.parse(fs.readFileSync(registry, 'utf8'));
  if (!Array.isArray(value.templates)) fail('templates.json 缺少 templates 数组。');
  return value.templates;
}

function getTemplate(templateId) {
  const template = loadRegistry().find((item) => item.id === templateId);
  if (!template) fail(`未找到模板：${templateId}。请先调用 list_study_sheet_templates。`);
  if (!outputDirectoryNames.has(template.output_dir)) fail(`模板 ${templateId} 的输出目录不在允许列表中。`);
  return template;
}

function templateFile(template) {
  const { templates } = resourcePaths();
  const file = path.resolve(templates, template.template_file);
  if (!within(file, templates) || path.extname(file) !== '.typ') fail('模板文件路径不合法。');
  if (!fs.existsSync(file)) fail(`模板文件不存在：${template.template_file}`);
  const actual = sha256(file);
  if (actual !== template.template_sha256) {
    fail(`模板完整性检查失败：${template.template_file} 已变化；请由管理员确认后更新注册表哈希。`);
  }
  return file;
}

function safeFilePart(value) {
  return requiredString(value, 'topic', { maxLength: 80 })
    .replace(/[\\/:*?"<>|\r\n]+/g, '-')
    .replace(/\s+/g, ' ')
    .replace(/^\.+|\.+$/g, '')
    .trim() || '未命名主题';
}

function validDate(value) {
  const date = requiredString(value, 'date', { maxLength: 10 });
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date) || Number.isNaN(Date.parse(`${date}T00:00:00Z`))) {
    fail('date 必须为有效的 YYYY-MM-DD。');
  }
  return date;
}

function nextSequence(outputDirectory) {
  let highest = 0;
  for (const entry of fs.readdirSync(outputDirectory, { withFileTypes: true })) {
    if (!entry.isFile()) continue;
    const match = /^(\d{3})-/.exec(entry.name);
    if (match) highest = Math.max(highest, Number(match[1]));
  }
  return String(highest + 1).padStart(3, '0');
}

function escapeTypstString(value) {
  return String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

function replaceLetString(source, name, value) {
  const pattern = new RegExp(`^#let ${name} = ".*"$`, 'm');
  return pattern.test(source) ? source.replace(pattern, `#let ${name} = "${escapeTypstString(value)}"`) : source;
}

function applyTemplatePayload(source, template, input, topic, date) {
  const body = requiredString(input.typst_body, 'typst_body', { maxLength: 120000 });
  let rendered = source;
  const metadata = input.metadata && typeof input.metadata === 'object' && !Array.isArray(input.metadata)
    ? input.metadata : {};

  if (template.id === 'daily-question') {
    const questionType = nullableString(metadata.question_type, 'metadata.question_type', { maxLength: 40 }) ?? '单选';
    const questionSource = nullableString(metadata.question_source, 'metadata.question_source', { maxLength: 120 }) ?? 'Physics Vault';
    const layout = metadata.layout === 'long' ? 'long' : 'short';
    rendered = replaceLetString(rendered, 'question-type', questionType);
    rendered = replaceLetString(rendered, 'topic', topic);
    rendered = replaceLetString(rendered, 'question-source', questionSource);
    rendered = replaceLetString(rendered, 'print-date', date ?? new Date().toISOString().slice(0, 10));
    rendered = rendered.replace(/^#let layout = ".*"$/m, `#let layout = "${layout}"`);
    const problemPattern = /#let problem = question-card\(\[[\s\S]*?\n\]\)\n\n#sheet\(problem, layout: layout\)/;
    if (!problemPattern.test(rendered)) fail('每日一题模板缺少可替换的题目内容区。');
    rendered = rendered.replace(problemPattern, `#let problem = question-card([\n${body}\n])\n\n#sheet(problem, layout: layout)`);
    return `${rendered}\n${generatedMarker}\n`;
  }

  if (template.id === 'knowledge-handout') {
    rendered = replaceLetString(rendered, 'topic', topic);
  }
  return `${rendered}\n\n${generatedMarker}\n// The block below is the only generated Typst payload.\n${body}\n`;
}

function outputDirectoryFor(template) {
  const { root } = resourcePaths();
  const outputDirectory = path.resolve(root, template.output_dir);
  if (!within(outputDirectory, root) || !outputDirectoryNames.has(path.basename(outputDirectory))) {
    fail('模板输出目录不合法。');
  }
  if (!fs.existsSync(outputDirectory)) fail(`模板输出目录不存在：${outputDirectory}`);
  return outputDirectory;
}

function outputTarget(template, outputDirectory, topic, date) {
  const sequence = nextSequence(outputDirectory);
  const filename = template.filename_pattern
    .replaceAll('{seq}', sequence)
    .replaceAll('{date}', date ?? new Date().toISOString().slice(0, 10))
    .replaceAll('{topic}', safeFilePart(topic));
  const sourcePath = path.resolve(outputDirectory, filename);
  if (!within(sourcePath, outputDirectory) || path.extname(sourcePath) !== '.typ') fail('生成文件名不合法。');
  return { sequence, sourcePath };
}

function requestFingerprint(templateId, topic, date, input) {
  const payload = JSON.stringify({
    template_id: templateId,
    topic,
    date: date ?? null,
    typst_body: input.typst_body,
    metadata: input.metadata ?? null,
  });
  return crypto.createHash('sha256').update(payload).digest('hex');
}

function findOperationResult(outputDirectory, requestedOperationId, fingerprint) {
  if (!requestedOperationId) return undefined;
  const marker = `${operationMarkerPrefix}${requestedOperationId}`;
  for (const entry of fs.readdirSync(outputDirectory, { withFileTypes: true })) {
    if (!entry.isFile() || path.extname(entry.name) !== '.typ') continue;
    const candidate = path.join(outputDirectory, entry.name);
    const source = fs.readFileSync(candidate, 'utf8');
    if (!source.startsWith(`${marker}\n`)) continue;
    const fingerprintMatch = /^\/\/ Physics Vault request-sha256: ([a-f0-9]{64})$/m.exec(source);
    if (!fingerprintMatch || fingerprintMatch[1] !== fingerprint) {
      fail(`operation_id ${requestedOperationId} 已用于不同的讲义内容，请改用新的 operation_id。`);
    }
    return candidate;
  }
  return undefined;
}

function createStudySheet(input) {
  const templateId = requiredString(input.template_id, 'template_id', { maxLength: 64 });
  const template = getTemplate(templateId);
  const topic = requiredString(input.topic, 'topic', { maxLength: 80 });
  const date = template.required_fields?.includes('date') ? validDate(input.date) : nullableString(input.date, 'date', { maxLength: 10 });
  const sourceTemplate = templateFile(template);
  const outputDirectory = outputDirectoryFor(template);
  const requestedOperationId = operationId(input.operation_id);
  const fingerprint = requestFingerprint(template.id, topic, date, input);
  const renderedBody = applyTemplatePayload(fs.readFileSync(sourceTemplate, 'utf8'), template, input, topic, date);
  const rendered = requestedOperationId
    ? `${operationMarkerPrefix}${requestedOperationId}\n// Physics Vault request-sha256: ${fingerprint}\n${renderedBody}`
    : renderedBody;
  if (input.dry_run === true) {
    const { sequence, sourcePath } = outputTarget(template, outputDirectory, topic, date);
    return {
      status: 'preview', template_id: template.id, source_path: sourcePath,
      output_directory: outputDirectory, sequence,
      template_integrity: 'passed', typst_payload_characters: input.typst_body.length,
      operation_id: requestedOperationId,
      message: '预览不会写入教学资源库。',
    };
  }

  const existingOperationPath = findOperationResult(outputDirectory, requestedOperationId, fingerprint);
  if (existingOperationPath) {
    return {
      status: 'existing', template_id: template.id, source_path: existingOperationPath,
      output_directory: outputDirectory, operation_id: requestedOperationId, idempotent: true,
      message: '相同 operation_id 已成功创建，本次返回原文件。',
    };
  }

  let sequence;
  let sourcePath;
  for (let attempt = 0; attempt < 20; attempt += 1) {
    ({ sequence, sourcePath } = outputTarget(template, outputDirectory, topic, date));
    try {
      fs.writeFileSync(sourcePath, rendered, { encoding: 'utf8', flag: 'wx' });
      break;
    } catch (error) {
      if (error?.code !== 'EEXIST' || attempt === 19) throw error;
    }
  }
  return {
    status: 'created', template_id: template.id, source_path: sourcePath,
    output_directory: outputDirectory, sequence, operation_id: requestedOperationId, idempotent: false,
    next_action: '调用 validate_and_compile_study_sheet 进行校验和 PDF 编译。',
  };
}

function sourceForValidation(template, sourcePath) {
  const outputDirectory = outputDirectoryFor(template);
  const source = path.resolve(requiredString(sourcePath, 'source_path', { maxLength: 1000 }));
  if (!within(source, outputDirectory) || path.extname(source) !== '.typ') {
    fail(`source_path 必须是 ${template.output_dir} 内的 .typ 文件。`);
  }
  if (!fs.existsSync(source)) fail(`学案源文件不存在：${source}`);
  if (!fs.readFileSync(source, 'utf8').includes(generatedMarker)) {
    fail('只允许校验由 Physics Vault 学案 MCP 创建的文件。');
  }
  return source;
}

function validateAndCompile(input) {
  const template = getTemplate(requiredString(input.template_id, 'template_id', { maxLength: 64 }));
  templateFile(template);
  const source = sourceForValidation(template, input.source_path);
  if (input.compile === false) return { status: 'validated', source_path: source, template_integrity: 'passed' };
  const pdfPath = source.replace(/\.typ$/i, '.pdf');
  if (fs.existsSync(pdfPath) && input.overwrite !== true) {
    return {
      status: 'pdf_exists', source_path: source, pdf_path: pdfPath,
      template_integrity: 'passed', overwrite_required: true,
      message: 'PDF 已存在，本次未覆盖；确认需要重新编译后以 overwrite=true 调用。',
    };
  }
  const result = spawnSync('typst', ['compile', source, pdfPath], { cwd: path.dirname(source), encoding: 'utf8', timeout: 120000 });
  if (result.error) fail(`无法启动 Typst：${result.error.message}`);
  if (result.status !== 0) fail(`Typst 编译失败：${result.stderr || result.stdout || '未返回错误信息'}`);
  return { status: 'compiled', source_path: source, pdf_path: pdfPath, template_integrity: 'passed' };
}

function listStudySheetTemplates() {
  const { root, templates } = resourcePaths();
  return {
    resource_root: root, template_root: templates,
    templates: loadRegistry().map(({ id, name, description, required_fields, editable_sections, output_dir, filename_pattern }) => ({
      id, name, description, required_fields, editable_sections, output_dir, filename_pattern,
    })),
  };
}

function auditTemplates() {
  return {
    checks: loadRegistry().map((template) => {
      const { templates } = resourcePaths();
      const source = path.resolve(templates, template.template_file);
      const actual = fs.existsSync(source) ? sha256(source) : null;
      return { id: template.id, file: template.template_file, passed: actual === template.template_sha256, expected_sha256: template.template_sha256, actual_sha256: actual };
    }),
  };
}

const tools = [
  { name: 'get_study_sheet_root_status', description: '检查教学资源库路径、模板注册表和受控输出目录。', inputSchema: { type: 'object', properties: {}, additionalProperties: false } },
  { name: 'list_study_sheet_templates', description: '列出可用的只读 Typst 模板和可编辑区，不返回模板正文。', inputSchema: { type: 'object', properties: {}, additionalProperties: false } },
  { name: 'create_study_sheet', description: '将结构化 Typst 内容注入经校验的模板，且只在教学资源库允许的成品目录创建 .typ。dry_run=true 时仅预览；传入 operation_id 可安全重试而不重复建档。', inputSchema: { type: 'object', properties: { template_id: { type: 'string' }, topic: { type: 'string' }, date: { type: 'string' }, typst_body: { type: 'string' }, metadata: { type: 'object', additionalProperties: true }, operation_id: { type: 'string', pattern: '^[A-Za-z0-9_-]{1,80}$' }, dry_run: { type: 'boolean', default: false } }, required: ['template_id', 'topic', 'typst_body'], additionalProperties: false } },
  { name: 'validate_and_compile_study_sheet', description: '再次校验模板完整性，并将 MCP 创建的 .typ 编译为 PDF；默认不覆盖已有 PDF。', inputSchema: { type: 'object', properties: { template_id: { type: 'string' }, source_path: { type: 'string' }, compile: { type: 'boolean', default: true }, overwrite: { type: 'boolean', default: false } }, required: ['template_id', 'source_path'], additionalProperties: false } },
  { name: 'audit_study_sheet_templates', description: '检查所有外置 Typst 模板是否仍与注册表 SHA-256 一致。', inputSchema: { type: 'object', properties: {}, additionalProperties: false } },
];

function content(data) {
  return { content: [{ type: 'text', text: JSON.stringify(data, null, 2) }] };
}

function handle(message) {
  if (message.method === 'initialize') {
    return { protocolVersion: message.params?.protocolVersion ?? '2025-03-26', capabilities: { tools: {} }, serverInfo: { name: 'physics-vault-study-sheet-workflow', version: '1.0.0' } };
  }
  if (message.method === 'tools/list') return { tools };
  if (message.method === 'tools/call') {
    const input = message.params?.arguments ?? {};
    const handlers = {
      get_study_sheet_root_status: () => ({ ...listStudySheetTemplates(), template_integrity: auditTemplates().checks }),
      list_study_sheet_templates: listStudySheetTemplates,
      create_study_sheet: () => createStudySheet(input),
      validate_and_compile_study_sheet: () => validateAndCompile(input),
      audit_study_sheet_templates: auditTemplates,
    };
    const handler = handlers[message.params?.name];
    if (!handler) fail(`未知工具：${message.params?.name}`);
    return content(handler());
  }
  return {};
}

const reader = readline.createInterface({ input: process.stdin, crlfDelay: Infinity });
reader.on('line', (line) => {
  let message;
  try {
    message = JSON.parse(line);
    const result = handle(message);
    if (message.id !== undefined) process.stdout.write(`${JSON.stringify({ jsonrpc: '2.0', id: message.id, result })}\n`);
  } catch (error) {
    if (message?.id !== undefined) {
      process.stdout.write(`${JSON.stringify({ jsonrpc: '2.0', id: message.id, error: { code: -32000, message: error.message } })}\n`);
    }
  }
});
